name: Healthcheck
run-name: Running Healthcheck service
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
